= Cyberismo ISMS essentials module

== Copyright

Copyright © Cyberismo Ltd and contributors 2024

== License and trademark policy

This is free content: you can redistribute it and/or modify it under the terms of the Creative Commons Attribution-ShareAlike 4.0 International Public License.

The use of Cyberismo trademark is governed by the Cyberismo open source trademark policy. See separate file TRADEMARK.adoc.

This content is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the Creative Commons Attribution-ShareAlike 4.0 International Public License in the separate LICENSE file for more details.

== Contributing

See separate file CONTRIBUTING.

== About the Cyberismo ISMS essentials module

The Cyberismo ISMS essentials module contains the basic building blocks for establishing an information security management system.
This includes example processes for

* asset management

* risk management

* incident management

along with the needed field types, link types, templates, workflows, registers, policy checks and progress metrics.

For a tutorial on how to get started with the Cyberismo ISMS essentials module, see the https://docs.cyberismo.com/cards/docs_y9v6f19e.html[ISMS essentials tutorial in Cyberismo documentation].
