= Cyberismo ISMS essentials module

== Copyright

Copyright © Cyberismo Ltd and contributors 2024

== License and trademark policy

This is free content: you can redistribute it and/or modify it under the terms of the Creative Commons Attribution-ShareAlike 4.0 International Public License.

The use of Cyberismo trademark is governed by the Cyberismo open source trademark policy. See separate file TRADEMARK.adoc.

This content is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the Creative Commons Attribution-ShareAlike 4.0 International Public License in the separate LICENSE file for more details.

== Contributing

See separate file CONTRIBUTING.

== About the Cyberismo ISMS essentials module

The Cyberismo ISMS essentials module contains the basic building blocks for establishing information security management system. 
This includes example processes for

* asset management

* risk management

* incident management

along with the needed field types, link types, templates, workflows, registers, policy checks and progress metrics.

== Using the Cyberismo ISMS essentials module

In order to use the base module content in your Cyberismo project, take the following steps:

* Clone this repository alongside your Cyberismo project
* Clone the base module alongside your Cyberismo project (`git clone git@githubcom:CyberismoCom/module-base.git`)
* Change to your project directory
* Import the base module and the ISMS essentials module content with

    cyberismo import module ../module-base
    cyberismo import module ../module-isms-essentials

* Start Cyberismo app on http://localhost:3000/

    cyberismo app

* Create start page for your ISMS using moduleHome template 

    CREATE NEW CARD -> ISMS home -> Create

For more details, see https://docs.cyberismo.com[Cyberismo documentation].
